---

#################################################################################
# Create password
#################################################################################

- name: "{{ansibleuser_username}} : Create random password value"
  shell: "tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo ''"
  register: randomstr

- name: "{{ansibleuser_username}} : Use random string as password"
  set_fact:
    pwdstr: "{{randomstr.stdout}}"
  when: password is not defined or password | length < 1

- name: "{{ansibleuser_username}} : Create encrypted password"
  shell: mkpasswd -m sha-512 {{pwdstr}}
  register: pwdstr_encrypted

- name: "{{ansibleuser_username}} : Remove secret variables"
  set_fact:
    pwdstr: ""


#################################################################################
# Create user
#################################################################################

- name: "{{ansibleuser_username}} : Create user"
  user:
    name: "{{ansibleuser_username}}"
    shell: /bin/bash
    password: "{{pwdstr_encrypted.stdout}}"
    home: "{{ansibleuser_home_dir}}"
    update_password: on_create

#################################################################################
# Set users sudo permissions
#################################################################################

- name: "{{ansibleuser_username}} : Add user to sudo group"
  user:
    name: "{{ansibleuser_username}}"
    groups: "{{ansibleuser_sudo_group}}"
    append: true # --> user is not removed from any other group

- name: "{{ansibleuser_username}} : Add user to sudo-nopasswd group"
  user:
    name: "{{ansibleuser_username}}"
    groups: "{{ansibleuser_sudo_nopwd_group}}"
    append: true # --> user is not removed from any other group

#################################################################################
# Allow user to be used as ssh target
#################################################################################

- name: "{{ansibleuser_username}} : Add user to ssh group"
  user:
    name: "{{ansibleuser_username}}"
    groups: "{{ansibleuser_ssh_group}}"
    append: true # --> user is not removed from any other group

#################################################################################
# Configure ssh for user
#################################################################################

- name: "{{ansibleuser_username}} : Create user's .ssh directory"
  file:
    path: "{{ansibleuser_home_dir}}/.ssh"
    state: directory
    owner: "{{ansibleuser_username}}"
    group: "{{ansibleuser_username}}"
    mode: 0700

- name: "{{ansibleuser_username}} : Set public key"
  lineinfile:
    path: "{{ansibleuser_home_dir}}/.ssh/authorized_keys"
    owner: "{{ansibleuser_username}}"
    group: "{{ansibleuser_username}}"
    mode: 0600
    line: "{{ansibleuser_public_key}}"
    create: yes
  when: ansibleuser_public_key is defined