---
- name: Install prerequsites
  apt:
    name:
      - curl
      - apt-transport-https
    state: present
    update_cache: yes

- name: install the microsoft package key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: install the microsoft repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
    state: present

- name: Install edge
  apt:
    name:
      - microsoft-edge-dev
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install additional tools for secret management
  apt:
    name:
      - gnome-keyring
    state: present
    update_cache: yes
    cache_valid_time: 3600