---
- name: Baseline
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: "Import variables from file"
      include_vars:
        file: ./../hosts/global_vars/accounts.yaml

    - name: Install whois to get mkpasswd tool (needed by role standard-user)
      apt:
        name: whois

    - name: Install unzip binary
      apt:
        name: unzip

    - name: Install fontconfig binary
      apt:
        name: fontconfig

    - name: Install and configure oh-my-posh
      include_role:
        name: app-ohmyposh

    - name: Configure vi systemwide
      include_role:
        name: cfg-vi

    - name: Create standard groups if needed
      include_role:
        name: cfg-standard-groups

    - name: Configure ansible
      include_role:
        name: cfg-ansible-user
      vars:
        username: "{{ansible_user}}"
        ssh_public_key: "{{ansible_user_config.ssh_public_key}}"

    - name: Configure SSH
      include_role:
        name: cfg-ssh

    - name: Create Users
      include_role:
        name: cfg-standard-user
      vars:
        username: "{{item.username}}"
        password: "{{item.password}}"
        user_home: "{{item.home_dir}}"
        make_sudo: "{{item.make_sudo}}"
        make_sudo_passwordless: "{{item.make_sudo_passwordless}}"
        user_id: "{{item.userid|int}}"
        ssh_public_key: "{{item.ssh_public_key}}"
        hostname_match: "{{item.hostname_match}}"
      when: accounts is defined and (item.hostname_match == "*" or inventory_hostname in item.hostname_match)
      loop: "{{ accounts }}"
      no_log: true #Supress output for security reasons