---
- name: Baseline
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: Install whois to get mkpasswd tool (needed by role standard-user)
      apt:
        name: whois

    - name: Install unzip binary
      apt:
        name: unzip

    - name: Install fontconfig binary
      apt:
        name: fontconfig

    - name: Create admin group if needed
      include_role:
        name: admin-group

    - name: Create Users
      include_role:
        name: standard-user
      vars:
        username: "{{item.username}}"
        password: "{{item.password}}"
        user_home: "{{item.home_dir}}"
        make_sudo: "{{item.make_sudo}}"
        make_sudo_passwordless: "{{item.make_sudo_passwordless}}"
        user_id: "{{item.userid|int}}"
        ssh_public_key: "{{item.ssh_public_key}}"
        hostname_match: "{{item.hostname_match}}"
      when: accounts is defined
      loop: "{{ accounts }}"
      no_log: false #Supress output for security reasons

    - name: Install and configure oh-my-posh
      include_role:
        name: app-ohmyposh