- name: GCP Test
  hosts: localhost
  gather_facts: no

  vars:
    service_account_file: ~/gcp_service_account.secret
    project: my-project
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:

    - name: Write serviceaccount to disk
      lineinfile:
        dest: "{{service_account_file}}"
        line: "{{gcp_dev}}"
        create: yes

      ###################
      # Here we implement gcp stuff
      ###################


    - name: Delete serviceaccount from disk
      file:
        path: "{{service_account_file}}"
        state: absent